export { default as logo} from '../assets/images/logo.svg'
export{ default as discord } from '../assets/images/Discord.png'
export{ default as vector } from '../assets/images/github.png'
export{ default as figma } from '../assets/images/Figma.png'
export { default as line }  from '../assets/images/Line.svg'
export { default as avatar } from '../assets/images/avatar.png'
export { default as logoline } from '../assets/images/Logoline.svg'
export { default as dots } from '../assets/images/Dots.svg'
export { default as fonimg} from '../assets/images/imgfon.svg'
export { default as logologo} from '../assets/images/logologo.svg'
export { default as frame} from '../assets/images/Frame1.svg'
export { default as imageavatar} from '../assets/images/Imageavatar.svg'
export { default as themeIcon} from '../assets/images/theme.svg'
export { default as email} from '../assets/images/Email.svg'
export { default as projectx } from '../assets/images/projectx.svg'
export { default as kahoot } from '../assets/images/kahoot.svg'
export { default as greyson } from '../assets/images/grayson.png'
export { default as airpods } from '../assets/images/aipords.png'
export { default as totem } from '../assets/images/totembo.png'
export { default as itemFon } from '../assets/images/fonItem.jpg'